layers: ["traversability_step", "traversability_slope", "traversability_roughness", "traversability", "elevation"]
gridmap_topic: "/traversability_estimation/traversability_map"
specific_files: []
combined_layers: ["traversability_slope", "traversability_step", "traversability_roughness"]
feature_matching_method: "TM" # Alternatives "ORB: SIFT: "FLANN: "SURF: "TM"
combined_only: True
write_stats_file: False
multiple: True